# Generated by Django 4.2.13 on 2024-07-05 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default=None, max_length=20, unique=True)),
                ('precio', models.PositiveIntegerField(default=None)),
                ('agregado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField(default=datetime.date(2024, 7, 5))),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('slug', models.SlugField(default=None, unique=True)),
            ],
        ),
    ]
