# Generated by Django 4.2.13 on 2024-07-04 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.BooleanField()),
                ('fecha_ingreso', models.DateField(default=datetime.date(2024, 7, 4))),
            ],
        ),
    ]
