# Generated by Django 4.2.13 on 2024-07-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comidas',
            name='agregado',
        ),
    ]
