# Generated by Django 4.2.13 on 2024-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0002_remove_comidas_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='agregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comidas',
            name='item',
            field=models.CharField(default='noname', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='comidas',
            name='precio',
            field=models.IntegerField(default=6500),
        ),
    ]
