# Generated by Django 4.2.13 on 2024-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0003_comidas_agregado_comidas_item_comidas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='item',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
