# Generated by Django 4.2.13 on 2024-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0004_alter_comidas_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
