# Generated by Django 4.2.13 on 2024-07-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0005_alter_comidas_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/item_photo'),
        ),
    ]
