# Generated by Django 4.2.13 on 2024-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0006_comidas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidas',
            name='slug',
            field=models.SlugField(default='comida', unique=True),
        ),
    ]
