# Generated by Django 4.2.13 on 2024-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0007_comidas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
