# Generated by Django 4.2.13 on 2024-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0008_alter_comidas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
