# Generated by Django 4.2.13 on 2024-07-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpage', '0009_alter_comidas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
